# Change these for each homework!
EXEC_NAME := hello
PROJ_NAME := hw1

build:
	echo "Nothing to compile."

run:
	python3 $(EXEC_NAME).py

archive:
	rm -f $(PROJ_NAME).zip
	zip $(PROJ_NAME).zip $(EXEC_NAME).py Makefile